controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_admin:
    path: /admin
    controller: App\Controller\AdminController::index

# routes/foot.yaml
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: ['GET', 'POST'] 
